### ISSUE TITLE
Add requirements using pip-compile and save to repo

### ISSUE THREAD

**Issue by svpernova09** [hippietilley/hephaestus#7]
Using https://github.com/jazzband/pip-tools create a `requirements.in` file, a`requirements_dev.in` file and use `pip-compile` to generate the `requirements.txt` and `requirements_dev.txt` files and add them to the repo.

**Comment by svpernova09** [comment]
PS I almost created this in LK...

**Comment by hippietilley** [comment]
Why not just make `requirements.txt` and `requirements_dev.txt`?

**Comment by svpernova09** [comment]
`pip-tools` will give detailed comments on not only package versions, but *which* packages are added by which other dependencies so it's easier to see from your requirements file where deps are coming from.
